BEGIN;
DO $$ BEGIN
  IF current_setting('running_test.local_fixture',true) IS DISTINCT FROM 'yes' THEN
    RAISE EXCEPTION 'Synthetic fixtures require running_test.local_fixture=yes in a disposable local database';
  END IF;
END $$;

CREATE TABLE public.articles (
  id serial PRIMARY KEY,
  source varchar NOT NULL,
  title varchar NOT NULL,
  url varchar NOT NULL UNIQUE,
  published_date timestamptz,
  content_hash varchar,
  status varchar DEFAULT 'NEW',
  created_at timestamptz DEFAULT now(),
  related_links jsonb,
  is_merged boolean DEFAULT false,
  category text,
  keywords text
);
CREATE TABLE public.collector_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at timestamptz NOT NULL,
  finished_at timestamptz NOT NULL,
  result varchar(20) NOT NULL CHECK (result IN ('SUCCESS','DEGRADED','FAILED')),
  collected_count integer NOT NULL DEFAULT 0,
  ai_output_count integer NOT NULL DEFAULT 0,
  db_attempted integer NOT NULL DEFAULT 0,
  db_succeeded integer NOT NULL DEFAULT 0,
  db_failed integer NOT NULL DEFAULT 0,
  source_health jsonb NOT NULL DEFAULT '{}',
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.collector_alert_state (
  singleton_id boolean PRIMARY KEY DEFAULT true CHECK (singleton_id IS TRUE),
  state jsonb NOT NULL DEFAULT '{"version":1,"activeIncidents":{},"events":[]}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_articles_url ON public.articles(url);
CREATE INDEX idx_articles_source_date ON public.articles(source,published_date);
CREATE INDEX idx_collector_runs_finished_at ON public.collector_runs(finished_at DESC);
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collector_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collector_alert_state ENABLE ROW LEVEL SECURITY;
CREATE POLICY "누구나 기사 읽기 가능" ON public.articles FOR SELECT USING (true);
CREATE POLICY "collector service can read runs" ON public.collector_runs FOR SELECT TO service_role USING (true);
CREATE POLICY "collector service can insert runs" ON public.collector_runs FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY "collector alert state service access" ON public.collector_alert_state FOR ALL TO service_role USING (true) WITH CHECK (true);
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON public.articles TO anon,authenticated,service_role;
REVOKE ALL ON public.collector_runs FROM PUBLIC,anon,authenticated;
GRANT INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON public.collector_runs TO anon,authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON public.collector_runs TO service_role;
REVOKE ALL ON public.collector_alert_state FROM PUBLIC,anon,authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON public.collector_alert_state TO service_role;
GRANT USAGE,SELECT ON SEQUENCE public.articles_id_seq,public.collector_runs_id_seq TO service_role;
INSERT INTO public.articles(source,title,url) VALUES ('fixture','Synthetic article','https://example.invalid/fixture');
INSERT INTO public.collector_runs(started_at,finished_at,result) VALUES ('2026-10-02T00:00:00Z','2026-10-02T00:01:00Z','SUCCESS');
INSERT INTO public.collector_alert_state(singleton_id) VALUES (true);

CREATE SCHEMA running_test;
CREATE FUNCTION running_test.medical_snapshot() RETURNS jsonb LANGUAGE sql AS $$
  SELECT jsonb_build_object(
    'schema_acl',(SELECT nspacl::text FROM pg_namespace WHERE nspname='public'),
    'tables',(SELECT jsonb_agg(jsonb_build_object('name',c.relname,'acl',c.relacl::text,'rls',c.relrowsecurity,'force',c.relforcerowsecurity) ORDER BY c.relname)
      FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','S')),
    'columns',(SELECT jsonb_agg(to_jsonb(x) ORDER BY x.table_name,x.ordinal_position) FROM information_schema.columns x WHERE x.table_schema='public'),
    'constraints',(SELECT jsonb_agg(jsonb_build_object('name',c.conname,'definition',pg_get_constraintdef(c.oid)) ORDER BY c.conname)
      FROM pg_constraint c JOIN pg_namespace n ON n.oid=c.connamespace WHERE n.nspname='public'),
    'indexes',(SELECT jsonb_agg(to_jsonb(x) ORDER BY x.indexname) FROM pg_indexes x WHERE x.schemaname='public'),
    'policies',(SELECT jsonb_agg(to_jsonb(x) ORDER BY x.tablename,x.policyname) FROM pg_policies x WHERE x.schemaname='public'),
    'triggers',(SELECT jsonb_agg(pg_get_triggerdef(t.oid) ORDER BY t.tgname) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND NOT t.tgisinternal),
    'defaults',(SELECT jsonb_agg(jsonb_build_object('owner',d.defaclrole,'type',d.defaclobjtype,'acl',d.defaclacl::text) ORDER BY d.defaclrole,d.defaclobjtype)
      FROM pg_default_acl d JOIN pg_namespace n ON n.oid=d.defaclnamespace WHERE n.nspname='public')
  );
$$;
CREATE TABLE running_test.baseline(snapshot jsonb NOT NULL);
INSERT INTO running_test.baseline SELECT running_test.medical_snapshot();
COMMIT;
