CREATE TABLE public.collector_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE NOT NULL,
    result VARCHAR(20) NOT NULL CHECK (result IN ('SUCCESS', 'DEGRADED', 'FAILED')),
    collected_count INTEGER NOT NULL DEFAULT 0,
    ai_output_count INTEGER NOT NULL DEFAULT 0,
    db_attempted INTEGER NOT NULL DEFAULT 0,
    db_succeeded INTEGER NOT NULL DEFAULT 0,
    db_failed INTEGER NOT NULL DEFAULT 0,
    source_health JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_collector_runs_created_at ON public.collector_runs(created_at DESC);

ALTER TABLE public.collector_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "collector runs are readable" ON public.collector_runs
    FOR SELECT USING (true);
